idf_component_register(
    SRCS
   "zb1.c"
    "light_driver.c"
    "display.c"
    "zigbee.c"
    "temp_chip.c"
INCLUDE_DIRS  "../components" "../managed_components" "/Users/gbatanov/work/esp-idf/esp-zigbee-sdk/components/esp-zigbee-lib/include" "/Users/gbatanov/work/esp-idf/esp-zboss-lib/include"
)
